version: '3'

services:

  mysql-dev:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flights
    ports:
      - "8000:3306"
    volumes:
      - ./sql_setup:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  myadmin-app:
    build:
        context: ./app_img
    image: adminapp_py
    volumes:
      - ./app_img/src:/app
    depends_on:
      - mysql-dev
    stdin_open: true

  myserver:
    build:
        context: ./server_img
    image: server_py
    volumes:
      - ./server_img/src:/app
    depends_on:
      - mysql-dev
    ports:
      - "8001:5000"

volumes:
  mysql_data: {}